name: Build the library
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    name: Build the plugin
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies on ubuntu
        run: |
          sudo apt update && sudo apt install -y ninja-build build-essential cmake libcurl4-openssl-dev

      - name: Configure
        run: |
          mkdir build && cd build
          mkdir artifacts
          cmake .. -G "Ninja" -DCMAKE_INSTALL_PREFIX=artifacts

      - name: Compiling
        working-directory: build
        run: |
          ninja -j$(nproc)

      - name: Installing
        working-directory: build
        run: |
          ninja install

  build-with-docker:
    name: Build the plugin with docker
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        tag: ['18.04', '20.04', '22.04']
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build
        run: docker build . -t jobcomp_report --build-arg ubuntu_version=${{ matrix.tag }}
